# Generated by Django 3.1.2 on 2020-12-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_opera'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title2',
            field=models.CharField(default='def1', max_length=255),
            preserve_default=False,
        ),
    ]
