# Generated by Django 3.1.2 on 2020-12-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_video_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title2',
        ),
    ]
