# Generated by Django 3.1.2 on 2020-12-06 07:00

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0004_remove_video_title2'),
    ]

    operations = [
        migrations.CreateModel(
            name='pv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_fk', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preferred_videos', gm2m.fields.GM2MField(through='main.pv', through_fields=['user', 'video', 'video_ct', 'video_fk'])),
            ],
        ),
        migrations.AddField(
            model_name='pv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user2'),
        ),
        migrations.AddField(
            model_name='pv',
            name='video_ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
