# Generated by Django 3.1.2 on 2020-10-25 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата правки')),
                ('archived', models.BooleanField(db_index=True, default=False, verbose_name='Архивирован')),
                ('protein', models.FloatField(default=0, verbose_name='Белки')),
                ('fat', models.FloatField(default=0, verbose_name='Жиры')),
                ('carbohydrate', models.FloatField(default=0, verbose_name='Углеводы')),
                ('ethanol', models.FloatField(default=0, verbose_name='Алкоголь')),
                ('organic_acids', models.FloatField(default=0, verbose_name='Органические кислоты')),
                ('polyols', models.FloatField(default=0, verbose_name='Многоатомные спирты')),
                ('fibre', models.FloatField(default=0, verbose_name='Пищевые волокна')),
                ('energy_value', models.FloatField(default=0, verbose_name='Калорийность')),
                ('popularity_general', models.PositiveIntegerField(default=0, verbose_name='Общее число использований')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Прием пищи',
                'verbose_name_plural': 'Приемы пищи',
            },
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_fk', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('component_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата правки')),
                ('archived', models.BooleanField(db_index=True, default=False, verbose_name='Архивирован')),
                ('protein', models.FloatField(default=0, verbose_name='Белки')),
                ('fat', models.FloatField(default=0, verbose_name='Жиры')),
                ('carbohydrate', models.FloatField(default=0, verbose_name='Углеводы')),
                ('ethanol', models.FloatField(default=0, verbose_name='Алкоголь')),
                ('organic_acids', models.FloatField(default=0, verbose_name='Органические кислоты')),
                ('polyols', models.FloatField(default=0, verbose_name='Многоатомные спирты')),
                ('fibre', models.FloatField(default=0, verbose_name='Пищевые волокна')),
                ('energy_value', models.FloatField(default=0, verbose_name='Калорийность')),
                ('popularity_general', models.PositiveIntegerField(default=0, verbose_name='Общее число использований')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('components', gm2m.fields.GM2MField(through='main.Portion', through_fields=['dish', 'component', 'component_ct', 'component_fk'])),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddField(
            model_name='portion',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AddField(
            model_name='portion',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meal'),
        ),
        migrations.AddField(
            model_name='meal',
            name='components',
            field=gm2m.fields.GM2MField(through='main.Portion', through_fields=['meal', 'component', 'component_ct', 'component_fk']),
        ),
    ]
