# Generated by Django 3.1.2 on 2020-10-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201025_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portion',
            options={'verbose_name': 'Порция', 'verbose_name_plural': 'Порции'},
        ),
        migrations.AlterField(
            model_name='portion',
            name='dish',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AlterField(
            model_name='portion',
            name='meal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.meal'),
        ),
    ]
