# Generated by Django 3.1.2 on 2020-12-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201201_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='m_components',
            new_name='components',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_components',
            new_name='components',
        ),
    ]
