# Generated by Django 3.1.2 on 2020-12-03 16:53

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('energy_value', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_fk', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('component_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('energy_value', models.FloatField(default=0)),
                ('components', gm2m.fields.GM2MField(through='main.Portion', through_fields=['dish', 'component', 'component_ct', 'component_fk'])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portion',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AddField(
            model_name='portion',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.meal'),
        ),
        migrations.AddField(
            model_name='meal',
            name='components',
            field=gm2m.fields.GM2MField(through='main.Portion', through_fields=['meal', 'component', 'component_ct', 'component_fk']),
        ),
    ]
